### ISSUE TITLE
Error on Blender 4.1

### ISSUE THREAD

**Issue by 3dcinetv** [BlenderBoi/timeline-buttons#1]
Traceback (most recent call last):
  File "E:\Program Files\blender-4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\blender-4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'timeline-buttons-1'

**Comment by BlenderBoi** [comment]
Oh uhh, I only tested on 4.2, I forgotten 4.1, will fix

**Comment by BlenderBoi** [comment]
@3dcinetv 
The solution is easy, either rename the folder in the zip file to timeline_buttons
or download it from this link

https://github.com/BlenderBoi/timeline-buttons/releases/tag/v1.0

Be sure to the  B_4_2_timeline-buttons_v1_0.zip
